messages:
  access-denied: '&cAccess denied!'
  no-console: 'This is for in-game players only.'
  show-header: '&eResults for this area:%br%'
  show-data: '&7[%time%]: &6%players%'
  invalid-number: '&cInvalid value!'
  out-of-range: '&cValue out of range!  (Valid values 0-99)'
  range-set: '&6Show range has been set to &e%value%'
  radius-set-general: '&6Player detection radius has been set to &e%value%'
  radius-set-specific: '&6Player detection radius has been set to &e%x% &7/ &e%y% &7/ &e%z%'
  radius-show-general: '&6Player detection radius currently at &e%value%'
  radius-show-specific: '&6Player detection radius currently at &e%x% &7/ &e%y% &7/ &e%z%'
  reloaded: '&6Configuration reloaded'
  no-results: '&6No creeper explosions logged in this area.'
  cleared: '&6Cleared &e%value% &6record(s).'  
  help-show: '&e/cpl show &7- &6Show any logs for this area'
  help-radius: '&e/cpl radius &7 (#) - &6Set radius for player detection when creeper explodes'
  help-showrange: '&e/cpl showrange &7 (#) - &6Set radius for logs to include when doing /cpl show'
  help-reload: '&e/cpl reload &7- &6Reloads config'
  help-clear: '&e/cpl clear &7- &6Clears all data in the show range from where you are'
  help-clear-console: '&e/cpl clear all &7- &6Clears all data%br%&e/cpl clear world &7(world) - &6Clears all data for specified world'
  